# Generated by Django 3.0.6 on 2020-05-20 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('super_user', '0002_auto_20200520_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=['%Y-%m-%d']),
        ),
    ]
