# Generated by Django 3.0.6 on 2020-05-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_user', '0003_auto_20200520_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, verbose_name=['%Y-%m-%d']),
        ),
    ]
